### PR TITLE
Add support for the output command

### LINKED ISSUE #40: Output Support
Hi - does this support output? (https://www.terraform.io/docs/commands/output.html)

### PR DESCRIPTION
**Pull request by david-obee**
## Description
This PR adds support for the `terraform output` command, detailed in https://www.terraform.io/docs/commands/output.html.

## Related Issue

https://github.com/cake-contrib/Cake.Terraform/issues/40

## Motivation and Context
This is a useful command that has been missing. While similar results are achievable by interpreting the output of the `terraform show` command, this is much more straight forward to use if you only need output values.

## How Has This Been Tested?

Covered the code with unit tests, as per the style of those for the other commands. All command line arguments used are tested.

This has been tested in a project Cake pipeline. A Terraform environment is created, after which we access two outputs using this new command.

## Screenshots (if appropriate):
_Not applicable._

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by megakid — APPROVED** [review]
Looks good to me

**Comment by reda-chakkour** [comment]
@david-obee @megakid Any reason this never landed?

**Comment by david-obee** [comment]
Hi @reda-chakkour, I'm not sure unfortunately, I don't have write access to the repo, so it needs one of the maintainers to approve and merge it

**Review by nils-a — APPROVED** [review]
LGTM!

**Comment by nils-a** [comment]
@david-obee your changes have been merged, thanks for your contribution :+1:

**Pull request merged**
