### PR TITLE
[WIP] Release 0.5.0

### PR DESCRIPTION
**Pull request by erikvanbrakel**
- Add support for .NET Standard.
- Add support for backend config overrides (#24)
- Add additional flags to terraform init (#25)
- Add Cake-Contrib Icon (#27, #29)
- Add support for env command (#26, #28)

### CODE REVIEW

**Comment by neillturner** [comment]
Thanks for this very useful plugin. 
I am keen to get the  backend config overrides for terraform init fauture as it will enable me to support different environments (test, prod etc) with the same terraform directory by specifying the state key.

**Comment by andycmaj** [comment]
@erikvanbrakel any idea when you plan on releasing 0.5.0?

**Comment by erikvanbrakel** [comment]
I don't have a real plan, but I've got a couple of days off before the weekend so I'll get it out there. In the meantime you can take the package from the myget feed to use the new stuff.

**Comment by andycmaj** [comment]
thanks, @erikvanbrakel!
Question about the pre-release package:

i'm seeing an error trying to use it in Cake.

```
The addin Cake.Http will reference Cake.Http.dll.
Installing NuGet package Cake.Terraform...
Executing: /Workspaces/appature/git/HubExchangeGateway/.tools/nuget.exe install "Cake.Terraform" -OutputDirectory "/Workspaces/appature/git/HubExchangeGateway/.tools/Addins" -Source "https://www.myget.org/F/erikvanbrakel/" -Prerelease -ExcludeVersion -NonInteractive
Could not find any assemblies compatible with .NETFramework,Version=v4.5.
Error: Cake.Core.CakeException: Failed to install addin 'Cake.Terraform'.
  at Cake.Core.Scripting.ScriptProcessor.InstallAddins (Cake.Core.Scripting.Analysis.ScriptAnalyzerResult analyzerResult, Cake.Core.IO.DirectoryPath installPath) [0x0010c] in <4cac44bd9f944138a8af690ea4654ac0>:0
  at Cake.Core.Scripting.ScriptRunner.Run (Cake.Core.Scripting.IScriptHost host, Cake.Core.IO.FilePath scriptPath, System.Collections.Generic.IDictionary`2[TKey,TValue] arguments) [0x000bf] in <4cac44bd9f944138a8af690ea4654ac0>:0
  at Cake.Commands.BuildCommand.Execute (Cake.CakeOptions options) [0x0002d] in <fad2e4944a9c44cc9683a2f0098b8e2e>:0
  at Cake.CakeApplication.Run (Cake.CakeOptions options) [0x0001d] in <fad2e4944a9c44cc9683a2f0098b8e2e>:0
  at Cake.Program.Main () [0x000dc] in <fad2e4944a9c44cc9683a2f0098b8e2e>:0
```

referenced using 
```
#addin nuget:https://www.myget.org/F/erikvanbrakel/?package=Cake.Terraform&prerelease
```

**Comment by andycmaj** [comment]
I think you might have to target a lower version of the full fx in order for this addin to work with non-coreclr cake.

**Comment by erikvanbrakel** [comment]
@andycmaj I just submitted a PR fixing this (works on my machine) #30. When the build is green I'll merge it.

**Comment by erikvanbrakel** [comment]
I'm going to merge #26, and I want to have #17 fixed. Then I'm ready to push 0.5.0

**Pull request merged**
